server:
  port: ${PORT:80}
spring:
  application:
    name: Clickstream Analytics Processor
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        database: ${AZURE_COSMOS_DATABASE}
        populate-query-metrics: true
  config:
    import:
      - optional:file:.env.infra[.properties]
custom:
  azure:
    eventhubs:
      clickstream:
        consumer-group: $Default
        event-hub-name: ${AZURE_EVENTHUB_NAME}
        storage-account-endpoint: ${AZURE_STORAGE_ACCOUNT_ENDPOINT}
        storage-container-name: ${AZURE_STORAGE_CHECKPOINT_CONTAINER}
        event-hub-namespace: ${AZURE_EVENTHUB_NAMESPACE}
        schema-group-name: ${AZURE_EVENTHUB_SCHEMA_GROUP}
        schema-name: ClickstreamEvent
        schema-version: 1
    disable-event-consumer: false
