name: dev-grafana-sidecar-deploy.yml
env: 
  IMAGE_NAME: grafana-alloy-sidecar
on:
  push:
    tags:
      - 'dev-sc-*'
  workflow_dispatch: 
jobs:
  build:
    name: Build sidecar docker image and push to ACR
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Login to Azure Container Registry
        run: az acr login --name ${{ vars.ACR_NAME }}
      - name: Build and push Docker image to ACR
        run: |
          cd grafana
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
  deploy:
    name: Deploy sidecar image to ACA
    runs-on: ubuntu-latest
    environment: development
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Azure CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - name: Update Azure Container App with new image
        run: |
          az containerapp update \
            --name ${{ vars.CONTAINER_APP_NAME }} \
            --container-name ${{ vars.CONTAINER_APP_SIDECAR_APP_NAME }} \
            --resource-group ${{ vars.RESOURCE_GROUP }} \
            --image ${{ vars.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
